name: Rocket
main: com.github.devil0414.rocket.plugin.RocketPlugin
depend: [Kotlin, WorldEdit]
authors: [sonogram70]
version: $pluginVersion
api-version: '1.16'
commands:
  rocket:
    permission: Rocket.command
    description: Rocket Command
    usage: /<command> help
permissions:
  Rocket.command:
    default: op
    description: Rocket Command Permission